//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessTable
    {
        public System.Guid ID_Table { get; set; }
        public System.Guid ID_Position { get; set; }
        public string AccessType { get; set; }
    
        public virtual DataBaseTable DataBaseTable { get; set; }
        public virtual Position Position { get; set; }
    }
}
