//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashRegisterAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashRegisterAccess()
        {
            this.Purchase = new HashSet<Purchase>();
        }
    
        public System.Guid ID_CashRegisterAccess { get; set; }
        public System.Guid ID_CashRegister { get; set; }
        public System.Guid ID_EmployeeSeller { get; set; }
        public System.Guid ID_Operation { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual CashRegister CashRegister { get; set; }
        public virtual CashRegisterOperation CashRegisterOperation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}
