//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.CashRegisterAccess = new HashSet<CashRegisterAccess>();
            this.EmployeeWorkLog = new HashSet<EmployeeWorkLog>();
            this.StoreOrder = new HashSet<StoreOrder>();
            this.MerchandiseAcceptanceLog = new HashSet<MerchandiseAcceptanceLog>();
            this.PerformedHeadOrder = new HashSet<PerformedHeadOrder>();
            this.PerformedStoreOrder = new HashSet<PerformedStoreOrder>();
            this.PerformedStoreOrder1 = new HashSet<PerformedStoreOrder>();
        }
    
        public System.Guid ID_Employee { get; set; }
        public System.Guid ID_Position { get; set; }
        public System.Guid ID_RealEstate { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string MiddleName { get; set; }
        public string Telephone { get; set; }
        public string Passport { get; set; }
        public string IDK { get; set; }
        public bool IsEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashRegisterAccess> CashRegisterAccess { get; set; }
        public virtual Position Position { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeWorkLog> EmployeeWorkLog { get; set; }
        public virtual RealEstate RealEstate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreOrder> StoreOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchandiseAcceptanceLog> MerchandiseAcceptanceLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformedHeadOrder> PerformedHeadOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformedStoreOrder> PerformedStoreOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformedStoreOrder> PerformedStoreOrder1 { get; set; }
    }
}
