//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeadOrder()
        {
            this.PerformedHeadOrder = new HashSet<PerformedHeadOrder>();
        }
    
        public System.Guid ID_HeadOrder { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public System.Guid ID_Position { get; set; }
        public System.Guid ID_StatusOrder { get; set; }
        public string AssignFor { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformedHeadOrder> PerformedHeadOrder { get; set; }
    }
}
