//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchandiseAcceptanceLog
    {
        public System.Guid ID_StoreOrder { get; set; }
        public System.Guid ID_AcceptManager { get; set; }
        public System.DateTime AcceptDate { get; set; }
        public int Weight { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LackLog LackLog { get; set; }
        public virtual StoreOrder StoreOrder { get; set; }
    }
}
