//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Component = new HashSet<Component>();
            this.Merchandise = new HashSet<Merchandise>();
            this.StoreOrders = new HashSet<StoreOrder>();
        }
    
        public System.Guid ID_Product { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Recipe { get; set; }
        public Nullable<int> CalorieContent { get; set; }
        public Nullable<int> Proteins { get; set; }
        public Nullable<int> Fats { get; set; }
        public Nullable<int> Carbohydrates { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<int> MinTemperature { get; set; }
        public Nullable<int> MaxTemperature { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Component> Component { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merchandise> Merchandise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreOrder> StoreOrders { get; set; }
    }
}
