//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public System.Guid ID_Purchase { get; set; }
        public System.Guid ID_Merchandise { get; set; }
        public System.Guid ID_CashRegisterAccess { get; set; }
        public int Weight { get; set; }
        public System.DateTime PurchaseDate { get; set; }
    
        public virtual Merchandise Merchandise { get; set; }
        public virtual CashRegisterAccess CashRegisterAccess { get; set; }
    }
}
