//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialProviderContract
    {
        public System.Guid ID_Contract { get; set; }
        public System.Guid ID_RawMaterial { get; set; }
        public System.Guid ID_MeasurementUnit { get; set; }
        public System.DateTime ManufactureDate { get; set; }
        public int Count { get; set; }
        public int PricePerCount { get; set; }
        public System.Guid ID_StatusContract { get; set; }
    
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
    }
}
