//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateContact
    {
        public System.Guid ID_RealEstateContact { get; set; }
        public System.Guid ID_RealEstate { get; set; }
        public System.Guid ID_Departament { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
    
        public virtual Departament Departament { get; set; }
        public virtual RealEstate RealEstate { get; set; }
    }
}
