//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOrder
    {
        public System.Guid ID_StoreOrder { get; set; }
        public System.Guid ID_Product { get; set; }
        public System.Guid ID_RealEstateStore { get; set; }
        public System.Guid ID_StoreManager { get; set; }
        public System.Guid ID_StatusOrder { get; set; }
        public System.DateTime InitialDate { get; set; }
        public int Weight { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual RealEstate RealEstate { get; set; }
        public virtual PerformedStoreOrder PerformedStoreOrder { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual MerchandiseAcceptanceLog MerchandiseAcceptanceLogs { get; set; }
        public virtual Product Product { get; set; }
    }
}
