//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableStructure
    {
        public System.Guid ID_Table { get; set; }
        public string ColumnName { get; set; }
        public string ColumnType { get; set; }
        public System.Guid ID_TableStructure { get; set; }
    
        public virtual DataBaseTable DataBaseTable { get; set; }
    }
}
